---

- hosts: all

  vars_files:
  - env_vars/general.yml

  roles:
   - ping_test
   - base
###########################   - install_python27
   - apache_httpd
   - mysql_db
   - backend_django_source
   - backend_django_config
   - httpd_config
########   - meteor_setup
########   - frontend_meteor_source
   - ejabberd_setup


