---

- name: Update all packages
  apt: update_cache=yes state=latest

- name: Install basic packages
  apt: name="{{ item }}" state=present
  with_items:
   - python-pip
   - build-essential
   - libpcre3-dev
   - git

- name: Directory to store OSS source-code
  become: yes
  become_method: sudo
  file:
    path: /srv/oss_sources
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
