---

- name: enable production settings
  copy:
    src: "__init__.py"
    dest: "{{ backend_server_path }}/hackchat/settings/__init__.py"

- name: Creating app log directory
  become: yes
  become_method: sudo
  file:
    dest: /var/log/waterbottle/
    state: directory
    owner: apache
    group: www
    mode: 0777

- name: Creating directory for static files
  become: yes
  become_method: sudo
  file:
    dest: /srv/static/
    state: directory
    owner: apache
    group: www
    mode: 0777

- name: Create python2.7 virtualenv with pip
  pip:
    chdir: "{{ backend_server_path }}"
    name: pip
    version: 8.1.2
    virtualenv: "{{ backend_virtualenv_path }}"

#    virtualenv_python: "/srv/oss_sources/COMPILED_PYTHON/bin/python2.7"

- name: Install requirements.txt
  pip:
    chdir: "{{ backend_server_path }}"
    requirements: requirements.txt
    virtualenv: "{{ backend_virtualenv_path }}"

- name: Execute manage.py collectstatic
  become: yes
  become_user: apache
  shell: /srv/sources/waterbottle_django/venv/bin/python2.7 manage.py collectstatic --noinput
  args:
    chdir: "{{ backend_server_path }}/"

- name: Delete existing django database
  become: yes
  become_method: sudo
  mysql_db: name=waterbottle state=absent

- name: Create empty django database
  become: yes
  become_method: sudo
  mysql_db: name=waterbottle state=present

- name: Execute manage.py migrate
  become: yes
  become_user: apache
  shell: /srv/sources/waterbottle_django/venv/bin/python2.7 manage.py migrate
  args:
    chdir: "{{ backend_server_path }}/"

#- name: copy over wsgi.py
#  copy:
#    src: "wsgi.py"
#    dest: "{{ backend_server_path }}/hackchat/wsgi.py"


# ref: http://stackoverflow.com/a/24068570/198660
- name: Create basic admin user
  become: yes
  become_user: apache
  shell: echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'myemail@example.com', 'password')" | /srv/sources/waterbottle_django/venv/bin/python2.7 manage.py shell
  args:
    chdir: "{{ backend_server_path }}/"

