---

# ref: http://stackoverflow.com/a/26598887/198660

- name: Install MySQL
  become: yes
  become_method: sudo
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
  - python-mysqldb
  - mysql-server

- name: Start the MySQL service
  become: yes
  become_method: sudo
  service:
    name: mysql
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  become: yes
  become_method: sudo
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy root.cnf.j2 to /etc/my.cnf
  become: yes
  become_method: sudo
  template: src=root.cnf.j2 dest=/etc/my.cnf

- name: Copy root.cnf.j2 to /root/.my.cnf
  become: yes
  become_method: sudo
  template: src=root.cnf.j2 dest=/root/.my.cnf

- name: Restart mysql service
  become: yes
  become_method: sudo
  service: name=mysql state=restarted enabled=yes


