---

- name: Clone frontend_meteor repository
  git:
    repo: "{{ frontend_repo }}"
    dest: "{{ frontend_server_path }}"
    version: "{{ frontend_tag }}"
    accept_hostkey: yes
    force: yes
    update: yes
